# Generated by Django 5.2.6 on 2025-09-28 10:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_appointment_fee_alter_appointment_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Short description or intro.')),
                ('content', models.TextField(help_text='Full health education content.')),
                ('resources_link', models.URLField(blank=True, help_text='Optional link to external resources', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Health Education Resource',
                'verbose_name_plural': 'Health Education Resources',
                'ordering': ['-created_at'],
            },
        ),
    ]
